# Mapping: Compositions

## Remove low-quality fish

```{r}
minimal_values <- resfinder_mapped_prop %>% 
  left_join(res_alphadiv) %>% 
  filter(species %in% c("Pig", "Chicken")) %>% 
  select(res_mapped_fragments, resf_pct, res_chao1) %>% 
  map_df(min) %>% 
  t %>% 
  as.data.frame() %>% 
  rownames_to_column("feature") %>% 
  rename(min_value = V1)

judge_fish <- resfinder_mapped_prop %>% 
  left_join(res_alphadiv) %>% 
  filter(species == "Fish") %>% 
  select(sample_id, res_mapped_fragments, resf_pct, res_chao1) %>% 
  pivot_longer(-sample_id, names_to = "feature", values_to = "value") %>%
  left_join(minimal_values) %>% 
  mutate(passed = value >= min_value) 

p_fishqc <- judge_fish %>% 
  left_join(livestock_sample_metadata) %>% 
  mutate(feature = case_when(feature == "res_mapped_fragments" ~ "Number of mapped fragments",
                   feature == "resf_pct" ~ "Percentage of mapped fragments",
                   feature == "res_chao1" ~ "Richness estimation (Chao1, AMR genes)")) %>% 
  ggplot(aes(y = value, x = sample_id, fill = passed)) +
  geom_bar(stat = "identity") +
  facet_grid(cols = vars(feature), rows = vars(explicit_country), scales = "free") +
  labs(x = "Sample ID", fill = "Passed quality threshold:") +
  coord_flip() +
  theme_light(base_size = 9) +
  theme(legend.position = "bottom",
        axis.title.x = element_blank())

p_fishqc

ggsave("supp_fishqc.pdf", plot = p_fishqc, 
       width = 17.7, height = 12, units = "cm")
```

```{r}
bad_fish <- judge_fish %>% 
  group_by(sample_id) %>% 
  summarise(total_passed = sum(passed)) %>% 
  filter(total_passed == 0) %>% 
  .$sample_id

# Remaining fish samples
livestock_sample_metadata %>% 
  filter(species == "Fish",
         sample_id %in% include_samples,
         ! sample_id %in% bad_fish) %>% 
  count(country)
```

```{r}
res_coda_long <- res_long %>% 
  filter(! sample_id %in% bad_fish)

heatmap_sample_metadata <- livestock_sample_metadata %>% 
  column_to_rownames("sample_id")
```

## Taxonomic composition

```{r}
taxa_mapping_count <- gen_mapstats %>% 
  left_join(select(gen_refdata, id, custom_group)) %>% 
  group_by(sample_id, custom_group) %>% 
  summarise(fragments_per_taxon = sum(fragmentCount)) %>% 
  ungroup() %>% 
  complete(custom_group, sample_id, fill = list(fragments_per_taxon = 0)) 

taxa_proportions_summary <- bind_rows(taxa_mapping_count, 
                                      rename(unmapped_df, fragments_per_taxon = fragments_per_db,
                                             custom_group = db_name)) %>%
  left_join(livestock_sample_metadata) %>% 
  mutate(taxon_pct = 100 * fragments_per_taxon / total_fragments)

taxa_wide <- taxa_proportions_summary %>% 
  select(custom_group, sample_id, fragments_per_taxon) %>% 
  spread(key = "custom_group", value = "fragments_per_taxon", fill = 0) %>%
  column_to_rownames("sample_id")

zerocorr_taxa_wide <- zCompositions::cmultRepl(taxa_wide, method = "SQ")

taxa_clr <- t(apply(zerocorr_taxa_wide, 1, function(x){log2(x) - mean(log2(x))}))

# taxa_dist <- dist(taxa_clr)

aldex_taxa_clr <- aldex.clr(t(taxa_wide), useMC = T)

mean_aldex_taxa_clr <- map(aldex_taxa_clr@analysisData, rowMeans) %>% 
  data.frame(., check.names = F) %>% 
  t

aldex_taxa_clr_breaks <- c(seq(min(mean_aldex_taxa_clr), 0, length.out = 51), 
                           seq(max(mean_aldex_taxa_clr) / 100, max(mean_aldex_taxa_clr), length.out = 50))

taxa_clr_breaks <- c(seq(min(taxa_clr), 0, length.out = 51), 
                     seq(max(taxa_clr) / 100, max(taxa_clr), length.out = 50))
```

```{r}
mapped_to_bact <- taxa_proportions_summary %>% 
  filter(custom_group %in% c("Archaea", "Bacteria", "Other Bacteria/Archaea")) %>% 
  group_by(sample_id) %>% 
  summarise(total_bact_prop = sum(taxon_pct))

p_bacpct <- mapped_to_bact %>% 
  left_join(livestock_sample_metadata) %>% 
  mutate(species = factor(species, levels = c("Chicken", "Pig", "Turkey", "Veal Calf", "Fish"))) %>% 
  ggplot(aes(x = explicit_country, y = total_bact_prop, fill = species)) +
  geom_boxplot(outlier.shape = 21) +
  facet_grid(cols = vars(species), scales = "free_x", space = "free_x") +
  scale_fill_manual(values = plot_colours$species) +
  labs(x = "Country", y = "% bacterial hits") +
  # ggtitle("Bacterial mapping proportion") +
  guides(fill = F) +
  theme_light(base_size = 9) +
  theme(panel.grid.major.x = element_blank())

p_bacpct
```


```{r}
pheatmap(taxa_clr,
         breaks = taxa_clr_breaks,
         annotation_row = select(heatmap_sample_metadata, species),
         annotation_colors = list(species = plot_colours$species),
         clustering_distance_rows = "euclidean",
         cutree_rows = 2,
         cluster_cols = F,
         show_rownames = F)
```

```{r}
mapped_taxa_wide <- taxa_proportions_summary %>% 
  filter(custom_group != "Unmapped") %>% 
  select(custom_group, sample_id, taxon_pct) %>% 
  spread(key = "custom_group", value = "taxon_pct", fill = 0) %>%
  column_to_rownames("sample_id")

zerocorr_mapped_taxa_wide <- zCompositions::cmultRepl(mapped_taxa_wide, method = "SQ")

mapped_taxa_clr <- t(apply(zerocorr_mapped_taxa_wide, 1, function(x){log2(x) - mean(log2(x))}))
# mapped_taxa_dist <- dist(mapped_taxa_clr)

mapped_taxa_clr_breaks <- c(seq(min(mapped_taxa_clr), 0, length.out = 51), 
                            seq(max(mapped_taxa_clr) / 100, max(mapped_taxa_clr), length.out = 50))
```


```{r}
pheatmap(mapped_taxa_clr,
         breaks = mapped_taxa_clr_breaks,
         annotation_row = select(heatmap_sample_metadata, species),
         annotation_colors = list(species = plot_colours$species),
         clustering_distance_rows = "euclidean",
         cutree_rows = 2,
         cluster_cols = F,
         show_rownames = F)
```

## Resistome Composition

### Gene level

```{r}
res_wide <- res_coda_long %>% 
  select(gene_id, sample_id, fragmentCount) %>% 
  spread(key = "gene_id", value = "fragmentCount", fill = 0) %>%
  column_to_rownames("sample_id")
```

```{r}
# GBM doesn't work - throws NAs before min threshold corrections, this leads
# to an error when evaluating the if statement
# zerocorr_res_wide <- zCompositions::cmultRepl(res_wide, method = "SQ",
#                                               output = "p-counts")
# 
# clr_res <- t(apply(zerocorr_res_wide, 1, function(x){log2(x) - mean(log2(x))}))
# 
# res_pca <- prcomp(clr_res)
# res_vars_pca <- res_pca$sdev^2 / sum(res_pca$sdev^2) * 100
# 
# res_heat_matrix <- clr_res
# 
# clr_res_breaks <- c(seq(min(clr_res), 0, length.out = 51), 
#                     seq(max(clr_res) / 100, max(clr_res), length.out = 50))
```

```{r}
# res_pca$x %>% 
#   data.frame() %>% 
#   rownames_to_column() %>% 
#   left_join(livestock_sample_metadata, by = c("rowname" = "sample_id")) %>% 
#   ggplot(., aes(x = PC1, y = PC2, fill = species)) +
#   stat_ellipse(geom = "polygon", alpha = 0.66) +
#   geom_hline(yintercept = 0, linetype = "dashed") +
#   geom_vline(xintercept = 0, linetype = "dashed") +
#   geom_point(shape = 21) +
#   scale_fill_manual(values = plot_colours$species) +
#   scale_colour_manual(values = plot_colours$species) +
#   labs(x = paste0("PC1: ", round(res_vars_pca[1] , 1), "% var."),
#        y = paste0("PC2: ", round(res_vars_pca[2] , 1), "% var.")) +
#   ggtitle("ResFinder gene-level PCA") +
#   theme_classic() +
#   theme(panel.border = element_rect(linetype = "solid", fill = NA),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         axis.line = element_blank())
```


```{r}
res_filtered_wide <- res_coda_long %>%
  left_join(livestock_sample_metadata) %>%
  filter(species != "Fish") %>%
  select(gene_id, sample_id, fragmentCount) %>%
  spread(key = "gene_id", value = "fragmentCount", fill = 0) %>%
  column_to_rownames("sample_id")

res_filtered_species <- data.frame("sample_id" = rownames(res_filtered_wide), stringsAsFactors = F) %>%
  left_join(livestock_sample_metadata) %>%
  .$species

filtered_aldex_res_iqlr <- aldex.clr(t(res_filtered_wide), 
                                    denom = "iqlr", conds = res_filtered_species)

filtered_iqlr_indices <- getDenom(filtered_aldex_res_iqlr)
iqlr_denom_names <- colnames(res_filtered_wide)[filtered_iqlr_indices]

res_species <- data.frame("sample_id" = rownames(res_wide), stringsAsFactors = F) %>%
  left_join(livestock_sample_metadata) %>%
  .$species

complete_iqlr_indices <- which(colnames(res_wide) %in% iqlr_denom_names)

aldex_res_clr <- aldex.clr(t(res_wide), 
                           denom = complete_iqlr_indices, 
                           conds = res_species)

viz_aldex_res_clr <- map(aldex_res_clr@analysisData, rowMeans) %>% 
  data.frame(., check.names = F) %>%
  t

viz_clr_long <- viz_aldex_res_clr %>% 
  as.data.frame() %>% 
  rownames_to_column("sample_id") %>% 
  pivot_longer(-sample_id, names_to = "gene_id", values_to = "clr") %>% 
  left_join(resfinder_metadata) %>%
  left_join(livestock_sample_metadata)

aldex_res_pca <- prcomp(viz_aldex_res_clr)
aldex_res_vars_pca <- aldex_res_pca$sdev^2 / sum(aldex_res_pca$sdev^2) * 100

# iqlr_res_clr <- aldex.clr(t(res_wide), conds_mm, useMC = T, denom = "iqlr")
# 
# mean_iqlr_res_clr <- map(iqlr_res_clr@analysisData, rowMeans) %>% 
#   data.frame(., check.names = F) %>%
#   t
# 
# iqlr_res_pca <- prcomp(mean_iqlr_res_clr)
# iqlr_res_vars_pca <- iqlr_res_pca$sdev^2 / sum(iqlr_res_pca$sdev^2) * 100
```


```{r}
p_pca <- aldex_res_pca$x %>% 
  data.frame() %>% 
  rownames_to_column() %>% 
  left_join(livestock_sample_metadata, by = c("rowname" = "sample_id")) %>% 
  mutate(species = factor(species, levels = c("Chicken", "Pig", "Turkey", "Veal Calf", "Fish"))) %>% 
  ggplot(., aes(x = PC1, y = PC2, fill = species)) +
  stat_ellipse(geom = "polygon", alpha = 0.66) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(shape = 21, size = 1) +
  scale_fill_manual(values = plot_colours$species, guide = guide_legend(title = NULL)) +
  scale_colour_manual(values = plot_colours$species, guide = guide_legend(title = NULL)) +
  labs(x = paste0("PC1: ", round(aldex_res_vars_pca[1] , 1), "% var."),
       y = paste0("PC2: ", round(aldex_res_vars_pca[2] , 1), "% var.")) +
  theme_classic(base_size = 9) +
  theme(panel.border = element_rect(linetype = "solid", fill = NA),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_blank(),
        legend.position = "bottom",
        legend.key.size = unit(0.3, "cm"),
        legend.box.spacing = unit(0.1, "cm"),
        legend.margin = margin(0.1, 0.1, 0.1, 0.1, "cm"))

p_pca
```

```{r}
clr_vars <- viz_clr_long %>% 
  group_by(short_gene) %>% 
  summarise(gene_var = var(clr)) %>% 
  ungroup() %>% 
  mutate(var_rank = row_number(desc(gene_var)))

p_genes <- aldex_res_pca$rotation %>% 
  data.frame() %>% 
  rownames_to_column() %>% 
  select(rowname, PC1, PC2) %>% 
  left_join(resfinder_metadata, by = c("rowname" = "gene_id")) %>% 
  left_join(clr_vars) %>% 
  filter(var_rank <= 15) %>%
  ggplot(., aes(x = PC1, y = PC2, fill = munk2018_amr_group)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_segment(aes(xend = PC1, yend = PC2, colour = munk2018_amr_group), 
               x = 0, y = 0,
               arrow = arrow(length = unit(0.15, "cm"))) +
  # geom_point(shape = 21, size = 1.25) +
  geom_label_repel(aes(label = short_gene),
                   size = 2.5, segment.size = 0.25,
                   label.padding = unit(0.085, "cm")) +
  labs(x = paste0("PC1: ", round(aldex_res_vars_pca[1] , 1), "% var."),
       y = paste0("PC2: ", round(aldex_res_vars_pca[2] , 1), "% var.")) +
  scale_fill_manual(values = plot_colours$new_amr_group, guide = guide_legend(title = NULL)) +
  scale_colour_manual(values = plot_colours$new_amr_group, guide = guide_legend(title = NULL)) +
  theme_classic(base_size = 9) +
  theme(panel.border = element_rect(linetype = "solid", fill = NA),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_blank(),
        legend.position = "bottom",
        legend.key.size = unit(0.3, "cm"),
        legend.box.spacing = unit(0.1, "cm"),
        legend.margin = margin(0.1, 0.1, 0.1, 0.1, "cm"))

p_genes
```

```{r}
# pca_legend <- get_legend(p_pca)

whole_shebang <- plot_grid(p_chao, 
                           p_stackedbar, 
                           plot_grid(p_pca, p_genes, nrow = 1, labels = c("c", "d")),
                           # pca_legend,
                           # axis = "lr", align = "v",
                           ncol = 1, rel_heights = c(0.5, 1, 0.6), labels = c("a", "b", NULL, NULL))

ggsave("fig_summary.pdf", plot = whole_shebang, width = 17.7, height = 17.7, units = "cm", device = cairo_pdf,
       family = "Arial")
```

```{r}
heatmap_res_metadata <- resfinder_metadata %>%
  column_to_rownames("short_gene")

# heat_propr <- propr::aldex2propr(aldex_res_clr, how = "phs")

aldex_heat_matrix <- viz_aldex_res_clr %>% 
  t %>% 
  as.data.frame() %>% 
  rownames_to_column("gene_id") %>% 
  left_join(select(resfinder_metadata, gene_id, short_gene)) %>% 
  left_join(clr_vars) %>% 
  filter(var_rank <= 100) %>% 
  select(-gene_id, -gene_var, -var_rank) %>% 
  column_to_rownames("short_gene") %>% 
  as.matrix()

samples_clust <- hclust(dist(viz_aldex_res_clr), method = "ward.D")
genes_clust <- hclust(dist(t(viz_aldex_res_clr)), method = "ward.D")

pheatmap(aldex_heat_matrix,
         color = magma(100),
         show_colnames = F,
         cluster_cols = samples_clust,
         clustering_distance_rows = "correlation",
         clustering_method = "ward.D",
         annotation_col = select(heatmap_sample_metadata, Country = explicit_country, Species = species),
         annotation_row = select(heatmap_res_metadata, `AMR Class` = munk2018_amr_group),
         annotation_colors = list(Species = plot_colours$species,
                                  Country = plot_colours$explicit_country,
                                  `AMR Class` = plot_colours$new_amr_group),
         filename = "supp_res_clustering.pdf",
         width = 1.3 * 17.7 / 2.54,
         height = 1.3 * 21 / 2.54,
         fontsize = 8,
         treeheight_row = 30,
         treeheight_col = 30)
```


```{r}
# iqlr_res_pca$x %>% 
#   data.frame() %>% 
#   rownames_to_column() %>% 
#   left_join(livestock_sample_metadata, by = c("rowname" = "sample_id")) %>% 
#   ggplot(., aes(x = PC1, y = PC2, fill = species)) +
#   stat_ellipse(geom = "polygon", alpha = 0.66) +
#   geom_hline(yintercept = 0, linetype = "dashed") +
#   geom_vline(xintercept = 0, linetype = "dashed") +
#   geom_point(shape = 21) +
#   scale_fill_manual(values = plot_colours$species) +
#   scale_colour_manual(values = plot_colours$species) +
#   labs(x = paste0("PC1: ", round(iqlr_res_vars_pca[1] , 1), "% var."),
#        y = paste0("PC2: ", round(iqlr_res_vars_pca[2] , 1), "% var.")) +
#   ggtitle("ALDEX IQLR: ResFinder gene-level PCA") +
#   theme_classic() +
#   theme(panel.border = element_rect(linetype = "solid", fill = NA),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         axis.line = element_blank())
```

```{r}
# pheatmap(res_heat_matrix,
#          breaks = clr_res_breaks,
#          annotation_row = select(heatmap_sample_metadata, country, species),
#          annotation_col = select(heatmap_res_metadata, munk2018_amr_group),
#          annotation_colors = list(species = plot_colours$species,
#                                   country = plot_colours$country,
#                                   munk2018_amr_group = plot_colours$munk2018),
#          clustering_distance_rows = "euclidean",
#          treeheight_row = 30,
#          treeheight_col = 30,
#          # cutree_rows = 5,
#          # cluster_cols = F,
#          show_rownames = F,
#          show_colnames = F)
```

### Class Level

```{r}
# class_wide <- res_coda_long %>% 
#   group_by(sample_id, amr_class) %>% 
#   summarise(class_fragments = sum(fragmentCount)) %>% 
#   ungroup() %>% 
#   select(amr_class, sample_id, class_fragments) %>% 
#   spread(key = "amr_class", value = "class_fragments", fill = 0) %>%
#   left_join(select(livestock_sample_metadata, sample_id, country, species)) %>%
#   arrange(species, country) %>%
#   select(-species, -country) %>%
#   column_to_rownames("sample_id")

# zerocorr_class_wide <- zCompositions::cmultRepl(class_wide, method = "SQ")
```

```{r}
# clr_class <- t(apply(zerocorr_class_wide, 1, function(x){log2(x) - mean(log2(x))}))
# 
# class_pca <- prcomp(clr_class)
# class_vars_pca <- class_pca$sdev^2 / sum(class_pca$sdev^2) * 100

# aldex_class_clr <- aldex.clr(t(class_wide), useMC = T)
# 
# mean_aldex_class_clr <- map(aldex_class_clr@analysisData, rowMeans) %>% 
#   data.frame(., check.names = F) %>%
#   t

```

```{r}
# class_pca$x %>% 
#   data.frame() %>% 
#   rownames_to_column() %>% 
#   left_join(livestock_sample_metadata, by = c("rowname" = "sample_id")) %>% 
#   ggplot(., aes(x = PC1, y = PC2, fill = species)) +
#   stat_ellipse(geom = "polygon", alpha = 0.66) +
#   geom_hline(yintercept = 0, linetype = "dashed") +
#   geom_vline(xintercept = 0, linetype = "dashed") +
#   geom_point(shape = 21) +
#   scale_fill_manual(values = plot_colours$species) +
#   scale_colour_manual(values = plot_colours$species) +
#   labs(x = paste0("PC1: ", round(class_vars_pca[1] , 1), "% var."),
#        y = paste0("PC2: ", round(class_vars_pca[2] , 1), "% var.")) +
#   ggtitle("ResFinder class-level PCA") +
#   theme_classic() +
#   theme(panel.border = element_rect(linetype = "solid", fill = NA),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         axis.line = element_blank())
```

```{r, eval=F}
# class_clr_long <- clr_class %>% 
#   data.frame() %>% 
#   rownames_to_column("sample_id") %>% 
#   gather(., key = "amr_class", value = "clr", -sample_id) %>% 
#   mutate(amr_class = if_else(amr_class == "Beta.Lactam", "Beta-Lactam",
#                              str_replace_all(amr_class, "\\.", "/")))
```

```{r, eval=F}
# class_clr_long %>% 
#   left_join(livestock_sample_metadata) %>%
#   group_by(country, species, amr_class) %>% 
#   mutate(n_group = dense_rank(desc(clr)),
#          x_group = (n_group - 1) %% 5,
#          y_group = -(ceiling((n_group / 5))),
#          y_lines = percent_rank(clr) + 1,
#          x_lines = 1) %>%
#   ggplot(aes(y = -n_group, x = country, fill = clr)) +
#   geom_tile(width = 0.9) + 
#   scico::scale_fill_scico(palette = "vik", direction = 1,
#                           limits = c(-1, 1) * max(abs(class_clr_long$clr))) +
#   facet_grid(rows = vars(amr_class), cols = vars(species), 
#              scales = "free",
#              space = "free_x",
#              switch = "y") +
#   theme_classic() +
#   theme(panel.border = element_blank(),
#         panel.spacing.x = unit(1.5, "pt"),
#         panel.spacing.y = unit(3, "pt"),
#         strip.text.y = element_text(angle = 180),
#         strip.background = element_blank(),
#         axis.line = element_blank(),
#         axis.text.y = element_blank(),
#         axis.title = element_blank(),
#         axis.ticks = element_blank(),
#         legend.position = "bottom")

# ggsave("roastme.png", width = 16.99, height = 16, units = "cm")
```

### Effects of Species/Country

## Bacterial Composition

### PCA

### Heatmaps

## Export for Determinant Analysis

```{r}
# zerocorr_res_long <- zerocorr_res_wide %>% 
#   rownames_to_column("sample_id") %>% 
#   pivot_longer(-sample_id, names_to = "gene_id", values_to = "fragmentCount")
# 
# gene_alr <- zerocorr_res_long %>% 
#   left_join(resfinder_metadata) %>% 
#   mutate(frags_per_bp = fragmentCount / gene_length_bp) %>% 
#   left_join(bact_hits) %>% 
#   mutate(gene_full_norm = frags_per_bp / bact_fragments,
#          gene_alr = log2(gene_full_norm)) %>% 
#   select(gene_id, sample_id, gene_alr) %>%
#   pivot_wider(names_from = "gene_id", values_from = "gene_alr",
#               values_fill = list(gene_alr = NA)) 
```

```{r}
# grouped_alr_long <- zerocorr_res_long %>% 
#   left_join(resfinder_metadata) %>% 
#   mutate(frags_per_bp = fragmentCount / gene_length_bp) %>% 
#   group_by(sample_id, amr_class) %>% 
#   summarise(class_frags_per_bp = sum(frags_per_bp)) %>% 
#   ungroup() %>% 
#   left_join(bact_hits) %>% 
#   mutate(class_full_norm = class_frags_per_bp / bact_fragments,
#          class_alr = log2(class_full_norm)) %>%
#   group_by(sample_id) %>% 
#   mutate(total_alr = log2(sum(class_full_norm))) %>% 
#   ungroup()
# 
# class_alr <- grouped_alr_long %>% 
#   select(amr_class, sample_id, class_alr) %>%
#   pivot_wider(names_from = "amr_class", values_from = "class_alr",
#               values_fill = list(class_alr = NA)) 
# 
# total_alr <- grouped_alr_long %>% 
#   distinct(sample_id, total_alr)
# 
# metadata_out <- res_coda_long %>% 
#   left_join(livestock_sample_metadata) %>% 
#   distinct(sample_id, country, species, farm_id, bio_rep, total_fragments)
```

```{r export-alr, eval=F}
# excel_out_path <- paste0("output/", lubridate::today(), "-EFFORT_MG_AMR_log2scale.xlsx")
# 
# l_export <- list(
#     "Total ALR" = total_alr,
#     "Drug class ALR" = class_alr,
#     "Gene ALR" = gene_alr,
#     "Sample Metadata" = metadata_out,
#     "Resfinder Metadata" = select(resfinder_metadata, - new_amr_group))
# 
# openxlsx::write.xlsx(l_export, file = excel_out_path, colWidths = "auto")
```

```{r}
# genus_wide <- bac_long %>% 
#   group_by(sample_id, genus_name) %>% 
#   summarise(fragments_per_genus = sum(fragmentCount)) %>% 
#   pivot_wider(id_cols = sample_id, names_from = genus_name, 
#               values_from = fragments_per_genus,
#               values_fill = list(fragments_per_genus = 0))
# 
# species_wide <- bac_long %>% 
#   group_by(sample_id, species_name) %>% 
#   summarise(fragments_per_genus = sum(fragmentCount)) %>% 
#   pivot_wider(id_cols = sample_id, names_from = species_name, 
#               values_from = fragments_per_genus,
#               values_fill = list(fragments_per_genus = 0))
# 
# bact_brief_taxonomy <- bac_long %>% 
#   select(species_name, genus_name, family_name, order_name, 
#          class_name, phylum_name, kingdom_name, superkingdom_name, db_name) %>% 
#   distinct() 
```

```{r export-frank, eval=F}
# all_samples_res_wide <- res_long %>% 
#   select(gene_id, sample_id, fragmentCount) %>% 
#   spread(key = "gene_id", value = "fragmentCount", fill = 0)
# 
# metadata_frank <- gen_mapstats %>%
#   left_join(livestock_sample_metadata) %>%
#   distinct(sample_id, explicit_country, country, species, farm_id, bio_rep, total_fragments)
# 
# frank_path <- paste0("output/", lubridate::today(), "-EFFORT_animal_count_data.xlsx")
# 
# l_frank <- list(
#     "Resfinder Counts" = all_samples_res_wide,
#     "Bact Species Counts" = species_wide,
#     "Sample Metadata" = metadata_frank,
#     "Resfinder Metadata" = select(resfinder_metadata, - new_amr_group),
#     "Bacteria Metadata" = bact_brief_taxonomy)
# 
# openxlsx::write.xlsx(l_frank, file = frank_path, colWidths = "auto")
```
