--- 
title: "Analysis Code for The European Livestock Resistome"
author: "Timo Röder & Patrick Munk"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    split_by: chapter
    self_contained: no
documentclass: book
description: "Code for The European Livestock Resistome study"
---

# Overview {-}

This book presents the R code used in the study **The European Livestock Resistome (Munk et al)[github.com]** 
and is meant to give the reader the possibility to reproduce (or built) upon the analyses presented in the manuscript.

We have tried to create a thorough documentation of the R code we wrote and used in the study to analyze the resistomes and 
welcome you to have a look at the whole process.

The vision, concept and systematic thinking behind this website truly belongs to Timo Röder,
who also wrote the large majority of code. Patrick Munk has maintained and updated to reflect later changes to the study and has tried to keep it in the spirit of Timo who has moved on to other exciting projects.

originally created by [Timo Röder](https://orcid.org/0000-0001-6841-4056) who deserves most credit.
Later updates, changes and additions have been carried out by [Patrick Munk](https://orcid.org/0000-0001-8813-4019) who has tried to finish the project in its intended spirit.



<!-- [Here](#intro) or \@ref(intro) for links-->
